### PR TITLE
Update SkillPackageManagement.ts

### LINKED ISSUE #1568: Deploying to Alexa fails with headers.find is not a function
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

When I do `jovo build:platform alexa` I expect the skill to be deployed to the alexa platform.

## Current Behavior

Currently I get: 

```
🚀 Deploying Alexa Skill
  ✖ Uploading skill package
                                                                                
x Error: --------------------------------------------------------------------------------
›                                                                                 
› Message:
›  headers.find is not a function
›                                                                                 
› Module:
›  JovoCliCore
›                                                                                 
›                                                                                 
› If you think this is not on you, you can submit an issue here: https://github.com/jovotech/jovo-cli/issues.

```

The behaviour seems to originate in `platforms/platform-alexa/src/cli/smapi/SkillPackageManagement.ts` line 96 (function parseImportUrl) where the headers value is of type object but is treated like an array. I can open a PR for this if desired.

## Your Environment

```
@jovotech/cli: 4.1.8 

Jovo packages of the current project :
  - @jovotech/db-filedb: 4.5.10  
  - @jovotech/framework: 4.5.10  
  - @jovotech/platform-alexa: 4.5.10  
  - @jovotech/plugin-debugger: 4.5.10  
  - @jovotech/server-express: 4.5.10  
  - @jovotech/cli-command-build: 4.1.8 [dev] 
  - @jovotech/cli-command-deploy: 4.1.8 [dev] 
  - @jovotech/cli-command-get: 4.1.8 [dev] 
  - @jovotech/cli-command-new: 4.1.8 [dev] 
  - @jovotech/cli-command-run: 4.1.9 [dev] 
  - @jovotech/cli-core: 4.1.9 [dev] 
  - @jovotech/filebuilder: 0.0.1 [dev] 
                                                                                
Environment:
  System:
    OS: macOS 13.4
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
```

### PR DESCRIPTION
**Pull request by jrglg**
Fixes  #1568

## Types of Changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by jrglg** [comment]
@jankoenig @aswetlow

**Comment by aswetlow** [comment]
Hey @jrglg 

Thank you for the PR. We'll take a look next week!

**Comment by ilovelinux** [comment]
See https://github.com/jovotech/jovo-cli/issues/357#issuecomment-1664711087

**Comment by aswetlow** [comment]
Hey @jrglg Thank you!
 
We chose https://github.com/jovotech/jovo-framework/pull/1580 for the same fix because it also checks for the correct aws-cli version.

**Comment by jrglg** [comment]
I agree.

Thank you

**Pull request closed without merging**
