### PR TITLE
♻️ Improve response for Facebook Messenger

### PR DESCRIPTION
**Pull request by m-ripper**
## Proposed changes
The response is now an array where each element is a response related to the processed event.

Example:
1. Request with a single event and text 'hello' received -> processed by the app -> The response is an array with a single item representing the response for the text 'hello'

2. Request with two events received (I) text 'hello' (II) text 'bye' -> I and II processed -> The response is an array with the first element representing the response for the text 'hello' and the second element representing the response for the text 'bye'.

Related to the same problem in #983.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by jankoenig** [comment]
Thanks! One quick question: How would this look like for serverless environments like AWS Lambda? e.g. the first event 'hello' would be handled by a different instance than the second event 'bye'. My assumption is that this would still work without a problem, the bot would still return 2 responses. Just wanted to keep this in mind as well

**Review by jankoenig — APPROVED** [review]
Just added some docs. Let me know if I missed anything. Thanks!

**Review by aswetlow — APPROVED** [review]

**Comment by m-ripper** [comment]
> Thanks! One quick question: How would this look like for serverless environments like AWS Lambda? e.g. the first event 'hello' would be handled by a different instance than the second event 'bye'. My assumption is that this would still work without a problem, the bot would still return 2 responses. Just wanted to keep this in mind as well

In Lambda it should also just open a single instance, which then handles both events because just a single invocation happens.

**Comment by jankoenig** [comment]
Ah got it, thank you. I misread and thought it was about multiple requests, not multiple events in a single request. I couldn't find anything in the Facebook docs regarding this behavior, do you have a link handy? Thanks

**Comment by jankoenig** [comment]
Found it! Ready to merge

**Pull request merged**
