### PR TITLE
:sparkles: check component availability

### PR DESCRIPTION
**Pull request by palle-k**
## Proposed Changes

This PR checks component availability when executing a handler.
While there has been a `isAvailable` property declared in `@Component`, it has never been checked.

## Types of Changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by jankoenig** [comment]
Thank you @palle-k!

I have 2 questions:
- Could you share a use case how you'd like to use this feature? This would help us evaluate the design/write documentation etc.
- You're throwing an error when a component isn't available. In your Jovo app, what would you do if the component weren't available and it threw an error, would you catch the error somewhere and then redirect to a different component? I'm thinking if there is maybe a different way to do that, e.g. don't take unavailable components into account during routing.

Appreciate your work!
Thanks,
Jan

**Comment by palle-k** [comment]
> Could you share a use case how you'd like to use this feature? This would help us evaluate the design/write documentation etc.

- One example could be that certain components are only available when the user has a valid access token. That way, everywhere in the component, we can guarantee that the user is actually logged in. 
- Another example could be that a component is only available if certain config options are set correctly. 
- Lastly, certain components may only be available when the device supports certain features.

So in general, I would say that the `isAvailable` function should be used to check invariants based on the current component config, the session data as well as user and device data.

Also, the primary reason why I made this PR is because I wanted to ensure that the `isAvailable` property, that has already been declared, is implemented and works as expected.

> You're throwing an error when a component isn't available. In your Jovo app, what would you do if the component weren't available and it threw an error, would you catch the error somewhere and then redirect to a different component? I'm thinking if there is maybe a different way to do that, e.g. don't take unavailable components into account during routing.

That's a good point. Handling it during routing sounds more elegant. That's also the reason why this PR is still a draft. 
If we do not take unavailable components into account during routing, what would you expect to happen when a redirect or delegation towards such a component occurs? That should still result in an error, right? 

In my Jovo app, I built a system of error boundaries (like error boundaries in React), where each component can have a `ERROR` method, which would catch the error and resume execution. The nearest error boundary would then also be responsible for catching this error. If you are interested, I could share the error boundary implementation as well.

**Comment by palle-k** [comment]
I have updated this PR to take `isAvailable` into account in the `RoutingExecutor`.

**Review by jankoenig — APPROVED** [review]
Looks great. Thank you! 🎉

**Review by aswetlow — APPROVED** [review]

**Pull request merged**
