### PR TITLE
add AplTemplates Override for Alexa Carousel and Card

### PR DESCRIPTION
**Pull request by jtfell**
## Proposed changes

Add an option for projects to override the default APL template for generic output types.

```ts
new AlexaPlatform({
    output: {
      genericOutputToApl: true,
      aplTemplates: {
        carousel: CAROUSEL_APL,
        card: CARD_APL
      },
    },
}),
```

to use custom APL document instead of the [default template](https://github.com/jovotech/jovo-framework/blob/v4/dev/platforms/platform-alexa/src/output/apl/Carousel.json).

For example, I want to use this template for my project:

```json
{
  "document": {
    "type": "APL",
    "version": "1.6",
    "import": [
      {
        "name": "alexa-layouts",
        "version": "1.3.0"
      }
    ],
    "mainTemplate": {
      "parameters": [
        "data"
      ],
      "item": {
        "type": "AlexaImageList",
        "headerTitle": "${data.header.title}",
        "headerAttributionImage": "${data.header.logo}",
        "listItems": "${data.items}",
        "hideOrdinal": true,
        "backgroundImageSource": "${data.backgroundImageUrl}",
        "height": "100%",
        "width": "100%",
        "theme": "light",
        "primaryAction": {
          "type": "SendEvent",
          "arguments": [
            "${data.selection}"
          ]
        }
      }
    }
  },
  "datasources": {
    "data": {
      "title": "",
      "backgroundImageUrl": "",
      "header": {
        "title": "",
        "logo": ""
      },
      "items": []
    }
  }
}
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jankoenig** [comment]
Oh, good one! I'll take a look :) thank you!

**Comment by jankoenig** [comment]
Thank you @jtfell, this looks very interesting. 

For consistency, could we also add this for [`card`](https://www.jovo.tech/marketplace/platform-alexa/output#card)? What do you think, @aswetlow?

**Comment by jtfell** [comment]
yep done @jankoenig

**Comment by jankoenig** [comment]
Thanks @jtfell! I'd like to make some (very minor) updates to the docs. Could you check "Allow edits from maintainers"?

**Comment by jtfell** [comment]
image

It looks like its already ticked to me

**Review by aswetlow — APPROVED** [review]

**Comment by jankoenig** [comment]
Thanks, I forgot to fetch your remote once again. Just updated the docs a bit, ready to go from my side ✅ 

Thank you again for this great contribution 🎉

**Review by jankoenig — APPROVED** [review]

**Pull request merged**
