### PR TITLE
❇️  Add event.$t middleware

### PR DESCRIPTION
**Pull request by rmtuckerphx**
## Proposed Changes

Add event.$t middleware to provide an easy way to listen to and track analytics on translation keys.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by rmtuckerphx** [comment]
Let's have a conversation to see if this is possible without making there be an `await this.$t(...)`

**Comment by jankoenig** [comment]
Thank you @rmtuckerphx! We'll take a look this week

**Comment by rmtuckerphx** [comment]
@jankoenig  I added this to a local project by hacking the file in node_modules and it worked fine. TypeScript doesn't like the PR though.

**Comment by rmtuckerphx** [comment]
Closing because of lack of interest.

**Pull request closed without merging**
