### PR TITLE
🐛 Fix duplicate request log

### PR DESCRIPTION
**Pull request by aswetlow**
The request log was printed twice. This PR removes the first one. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by m-ripper — APPROVED** [review]

**Comment by jankoenig** [comment]
Thanks! I'm using this to finish up the logging docs.

I have a few questions about the default config:

* `logging: undefined` -> could you elaborate what this means?
* `space: '   ',` -> what does this do?

Thank you

**Comment by jankoenig** [comment]
One more question: Should we rename the following properties to adhere to our guidelines that config properties shouldn't be verbs?

* maskRequestObjects -> maskedRequestObjects
* excludeRequestObjects -> excludedRequestObjects
* Same for responses

Any other ideas?

**Comment by aswetlow** [comment]
Thanks for the feedback.

`space` is the third parameter of the `JSON.stringify` function. It's the indentation of the JSON string. I think that `indentation` is a better property name.

* Changed to `maskedRequestObjects`, `maskedResponseObjects`, `excludedRequestObjects`,`excludedResponseObjects`
* Changed `space` to `indentation`
* Removed `logging`

Here's the current version:

```typescript
export interface BasicLoggingConfig extends PluginConfig {
  request?: boolean;
  response?: boolean;
  requestObjects?: string[];
  responseObjects?: string[];
  maskedRequestObjects?: string[];
  maskedResponseObjects?: string[];
  maskValue?: any;
  excludedRequestObjects?: string[];
  excludedResponseObjects?: string[];
  styling?: boolean;
  indentation?: string;
  colorizeSettings?: {
    colors: {
      BRACE?: string;
      BRACKET?: string;
      COLON?: string;
      COMMA?: string;
      STRING_KEY?: string;
      STRING_LITERAL?: string;
      NUMBER_LITERAL?: string;
      BOOLEAN_LITERAL?: string;
      NULL_LITERAL?: string;
    };
  };
}
```

**Review by jankoenig — APPROVED** [review]
Thank you! Docs are ready ✅

**Pull request merged**
