### PR TITLE
Add google res getters

### PR DESCRIPTION
**Pull request by natrixx**
## Proposed changes
add the following initial google specific response getters:

hasSuggestionChips()
getSuggestionChips()
hasDisplayText()
getDisplayText()

I plan to add more, but want to make sure I am on the right track, and keep the PR's manageable :) 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x ] My change requires a change to the documentation
- [ x] I have updated the documentation accordingly
- [x ] I have added tests to cover my changes
- [x ] All new and existing tests passed

### CODE REVIEW

**Comment by aswetlow** [comment]
Thank you, Nate!

There's one thing I would edit. We can use up to 8 suggestion chips. We need to make the `hasSuggestionChips(chipOne?: string, chipTwo?: string, chipThree?: string):` more flexible.

Here's a code sample what I have in mind. (barely tested)
```typescript
hasSuggestionChips(...chips: string[]){
    const suggestionChipArray = this.getSuggestionChips();

    if (!suggestionChipArray) {
        return false;
    }
    for (let i = 0; i < chips.length; i++) {
        if (!suggestionChipArray[i] || chips[i] !== suggestionChipArray[i].title) {
            return false;
        }
    }

    return true;
}

```

**Comment by natrixx** [comment]
ooh good catch, I remember seeing that long ago and far way, but had forgotten. 

I will work on this and see how it goes, thanks!

**Comment by natrixx** [comment]
Ok @aswetlow - that suggestion appears work great! I added a couple more tests to include a full array of options. I think that along with the previous tests with combos of up to 3 items in the array should be enough coverage. Thoughts?

**Comment by aswetlow** [comment]
Perfect! Thank you

**Pull request merged**
