### PR TITLE
Add AccountLinkCardOutput for alexa

### LINKED ISSUE #1231: Show account linking card for alexa
Hey there! I just wanted to migrate from v3 to v4 to have the cool new component structure.
Unfortunately, I struggle at the beginning with integrating the Alexa account linking.

## I'm submitting a...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

The account linking should be documented for v4.

## Current Behavior

The method `showAccountLinkingCard` doesn't seem to exist anymore, and I also don't found any documentation about showing the card.

## Your Environment

* Jovo Framework version used: 4.2.1

### PR DESCRIPTION
**Pull request by rmtuckerphx**
## Proposed changes

Add AccountLinkCardOutput for alexa
Resolves jovotech/jovo-framework#1231

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ x ] My code follows the code style of this project
- [ x ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ x ] All new and existing tests passed

### CODE REVIEW

**Comment by aswetlow** [comment]
Hey @rmtuckerphx 
Thank you for the PR.

Just an idea. Would it be more consistent if the class name would be `LinkAccountCardOutput` ?  cc @jankoenig

**Comment by jankoenig** [comment]
Thank you for the PR @rmtuckerphx!

I agree with @aswetlow that `LinkAccountCardOutput` would be more consistent with the Alexa naming.

I just rebased to `v4/dev`. `v4/latest` is the branch that contains the code of the latest NPM version.

I'd like to add docs for this PR, but for this, could you create a separate branch as opposed to `v4/latest` in your fork? Our convention usually is `v4/feature/<feature`, for example `v4/feature/linkaccountcard` (I just added some docs that explain this convention #1236). Then I'll be able to check it out and push doc updates.

Thanks!

**Comment by jankoenig** [comment]
Hi @rmtuckerphx, do you have the time to make the updates or should we close the PR for now?

Thanks,
Jan

**Comment by rmtuckerphx** [comment]
Just saw this again. I'll try to work on it this weekend.

**Comment by rmtuckerphx** [comment]
Replaced with https://github.com/jovotech/jovo-framework/pull/1291

**Pull request closed without merging**
