### PR TITLE
Add Alexa Getters `hasStandardCard` and `hasSimpleCard`

### PR DESCRIPTION
**Pull request by natrixx**
## Proposed changes
Add Alexa Getters `hasStandardCard` and `hasSimpleCard` back in. Jovo V1 had these and are useful for unit testing. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x ] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x ] I have added tests to cover my changes
- [x ] All new and existing tests passed

### CODE REVIEW

**Comment by aswetlow** [comment]
Hey @natrixx, 
thank you for this great PR. I made a few small changes (optional parameters). Will merge it when you're ready

**Comment by natrixx** [comment]
Thanks @aswetlow , looks good to me! One question though, the tests I added have some cases where I did not send all the params, but there was no error. Should there have been since the params were not yet set to optional?

**Comment by aswetlow** [comment]
```typescript
const simpleCardResponse = AlexaResponse.fromJSON(_cloneDeep(simpleCard));
expect(simpleCardResponse.hasSimpleCard()).toBe(true);`
```
`simpleCardResponse` is implicitly of type `any` here. 

```typescript
const simpleCardResponse: AlexaResponse = AlexaResponse.fromJSON(_cloneDeep(simpleCard));
expect(simpleCardResponse.hasSimpleCard()).toBe(true);`
```
This one won't work.

**Comment by natrixx** [comment]
Interesting. I think that makes sense. However, I change my test as you noted above:

```
const simpleCardResponse: AlexaResponse = AlexaResponse.fromJSON(_cloneDeep(simpleCard));
expect(simpleCardResponse.hasSimpleCard()).toBe(true);
```

and removed reverted your optional params, and I noticed my editor (VSCode) totally picked up that I was missing required params. When I ran the test though, it still passed. It may not be anything to be concerned about, but just want to be sure :)

**Pull request merged**
