### PR TITLE
:sparkles: Add Redis Db

### PR DESCRIPTION
**Pull request by rmtuckerphx**
## Proposed Changes

Add Database integration for Redis including entry splitting and TTL. Users of the plugin have the ability to encrypt Redis values without that code being part of the plugin.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by rmtuckerphx** [comment]
@jankoenig @aswetlow How do we solve this build error?

`/node_modules/@redis/client/dist/lib/client/socket.d.ts(39,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.`

**Comment by rmtuckerphx** [comment]
Will removing `tsconfig.build.esm5.json` from `db-redis` solve this?
What is the impact?

**Comment by aswetlow** [comment]
Could you add `"skipLibCheck": true` to `tsconfig.build.esm5.json`? This should solve this issue.

**Comment by aswetlow** [comment]
What is the latency for `connect()` and `disconnect()`?

**Comment by rmtuckerphx** [comment]
@aswetlow 
Here are some timings for Redis `connect` and `disconnect`:

getDbItem - Redis connect: 247.458ms
getDbItem - Redis disconnect: 5.134ms
saveData - Redis connect: 160.305ms
saveData - Redis disconnect: 1.051ms

getDbItem - Redis connect: 238.067ms
getDbItem - Redis disconnect: 0.911ms
saveData - Redis connect: 143.946ms
saveData - Redis disconnect: 0.931ms

**Comment by aswetlow** [comment]
Would it make sense to keep the connection alive after getDbItem and reuse it in saveData? At least for the time of the request. You could store the `client` in `jovo`. This would save ~150ms in latency. 

We could improve it, even more, by using connection pools. This is something that could be done in the future.

**Comment by rmtuckerphx** [comment]
@aswetlow I vote to optimize in the future. This is something that I need immediately.

**Review by jankoenig — APPROVED** [review]
Looks great, thank you!

**Review by aswetlow — APPROVED** [review]

**Comment by jankoenig** [comment]
Thank you @rmtuckerphx 🎉

**Pull request merged**
