### PR TITLE
add `getLocation` and `getAddress` to AlexaDevice

### PR DESCRIPTION
**Pull request by jtfell**
## Proposed changes

Hey Jovo team, I've been having a look at the new architecture for v4 and decided to implement the device location API for Alexa as a learning exercise. It's mostly a port from the v3 implementation merged with the new AlexaApi abstraction in v4. Any feedback welcome, I'll probably be getting around to the google version of this soon (and maybe moving onto the media player at some point as well).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by aswetlow** [comment]
Hey @jtfell  

Thank you for the PR. Currently, we're busy preparing the beta release tomorrow. We'll have a deeper look after that.

**Comment by jtfell** [comment]
Hey @rubenaeg @aswetlow - are you interested in adding this feature to v4? We need it to migrate to v4 so are keen to get it merged

**Comment by jankoenig** [comment]
Hi @jtfell, thanks for reminding us to take a look! Going to do so this week.

Thank you,
Jan

**Comment by jtfell** [comment]
hi @jankoenig, I've cleaned this PR up a bit

**Review by aswetlow — APPROVED** [review]

**Comment by aswetlow** [comment]
Oh sorry, this one got lost. 

Thanks for the updates.

**Review by aswetlow — CHANGES_REQUESTED** [review]
I missed one thing. 

I would suggest to move `getDeviceLocation` and `getDeviceAddress` from `AlexaUser` to `AlexaDevice`

**Comment by jankoenig** [comment]
> I missed one thing.
> 
> I would suggest to move `getDeviceLocation` and `getDeviceAddress` from `AlexaUser` to `AlexaDevice`

I agree. Would be great to access it with something like `this.$alexa.$device.getLocation()` instead of `this.$alexa.$user.getDeviceLocation()`.

What do you think?

**Comment by jtfell** [comment]
Great suggestion @aswetlow, totally agree - I've made the change.

**Comment by jankoenig** [comment]
Perfect, thank you @jtfell! 🚀 

 I'll try to finish the docs on Monday or Tuesday

**Review by aswetlow — APPROVED** [review]

**Comment by jankoenig** [comment]
Hey @jtfell,

I finally finished the docs for this. Could you take a look and see if I missed anything (or got anything wrong)?

Otherwise, good to go from my side.

Thank you!

**Review by jankoenig — APPROVED** [review]

**Comment by jtfell** [comment]
Cheers @jankoenig - LGTM

**Pull request merged**
