### PR TITLE
AWS Lex V1 plugin - beta version

### PR DESCRIPTION
**Pull request by kouz75**
## Proposed changes

Beta version of Jovo Lex plugin.
The plugin works with AWS Lex (test on version 1) and AWS connect
I will provide some documentation on how to build a callbot with Jovo/AWS Connect/Lex later.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project
- [x] My change requires a change to the documentation 
- [x] I have updated the documentation accordingly (I add a javascript code sample)
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by aswetlow** [comment]
Hey @kouz75 
Thank you for the PR! Excited to try it myself.

Could you pull the latest version of the framework? It would eliminate a lot of the conflicted files.

**Comment by aswetlow** [comment]
Awesome. Conflicting files are gone. Could you provide a small getting-started guide?

**Comment by kouz75** [comment]
I'm on it.

**Comment by kouz75** [comment]
I had a readme file in the plugin folder.

**Comment by aswetlow** [comment]
Hey, thanks again!

I have a few notes:

1) type middleware
``` if (lexRequest.getIntentName() === 'greeting') {
      // intent by default in every project that has "hello" etc. as utterance
      lex.$type = {
        type: EnumRequestType.LAUNCH,
      };
    } else if (lexRequest.getIntentName() === 'goodbye') {
      lex.$type = {
        type: EnumRequestType.END,
      };
    } else {
      lex.$type = {
        type: EnumRequestType.INTENT,
      };
    }
```
I'm not sure about that. The developer would need to have fixed intents (goodbye, greeting). 
LAUNCH: Is there a smoother way to detect requests similar to LaunchRequest on Alexa? Via session attributes for example?
END: I would recommend using our basic intent mapping. Also, AMAZON.StopIntent is supported by Lex.


2.) ask/tell
I tried our helloworld template, but it throws on `ask`

User: Hello
LexBot: Hello World! What's your name?

User: My name is max
LexBot: <ERROR>

```
if (tell) {
      _set(response, 'dialogAction', {
        type: 'Close',
        fulfillmentState: 'PlainText',
        message: {
          contentType: 'SSML',
          content: tell.speech,
        },
      });
    }
    const ask = output.ask;
    if (ask) {
      _set(response, 'dialogAction', {
        type: 'ElicitIntent',
        message: {
          contentType: 'PlainText',
          content: ask.speech,
        },
      });
      _set(response, 'sessionAttributes', lex.$session.$data);
    }
```
We should be consistent here. `tell` is of type SSML, `ask` of type PlainText. This could also be the reason for the error. It expects SSML but gets plaintext without the `<speak></speak>` tags

Let me know if you have further questions.

**Comment by kouz75** [comment]
Hi,

for the middleware part.
this part is a copy of another plugin ... I think we can remove this code :

Compare with Alexa, there isn't LaunchIntent. 
the first prompt have to be display directly on the web interface. if not, we will have to call lex with an empty request just to get the first prompt but with AWS Connect we won't be able to do this first call.
-> I propose to remove this code
State/user data/session data set in LaunchIntent must be set somewhere else for the first Lex  request. 
Maybe in NEW_SESSION intent.

For the StopIntent:
We will never received the intent AMAZON.StopIntent but a custom name define by the user in the LEX console.
-> I propose to remove this code

**Comment by aswetlow** [comment]
Thanks for the update!

I've never used Amazon Connect. What's the first request of the call? Or is an intro text you define in the Connect Console?

Ah, I see. Creating AMAZON.StopIntent requires a custom name, which needs to be mapped in the app.

This is the error I get:
image

It works after changing the `tell` part to 
``` _set(response, 'dialogAction', {
                type: 'Close',
                fulfillmentState: 'Fulfilled',
                message: {
                    contentType: 'PlainText',
                    content: tell.speech,
                },
            });
            ```

Could you look into it?

**Comment by kouz75** [comment]
On AWS Connect, you need to : 
 - set your locale and the voice 
 - define the first prompt. it will replace Alexa LaunchIntent
then you can wait for customer input. you should have a Connect model similar to: 
Capture d’écran 2021-04-15 à 13 52 38

**Comment by aswetlow** [comment]
Thank you!

I will merge and do minor changes (`__JOVO_NEW_SESSION__` => `_JOVO_NEW_SESSION_`) after that. We're planning to publish it to NPM later today.

**Pull request merged**
