### PR TITLE
Update response.md

### PR DESCRIPTION
**Pull request by VoiceFirstTech**
## Proposed changes

the docs state .getSpeech() does not return <speak> tags 
However, .getSpeech() does return <speak> tags 

image

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x ] My code follows the code style of this project
- [ x] My change requires a change to the documentation
- [x ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jankoenig** [comment]
Hi there, thank you! We think this is rather a bug in the code than a docs issue. We're working on updating the code so that it returns the speech withouth the `speak` tags. What do you think?

**Comment by VoiceFirstTech** [comment]
Perfect! 
 <speak> Let's get rid of those tags </speak>

we can close the issue if the change is in the backlog :+1:

**Comment by jankoenig** [comment]
Let's keep this open so we stay motivated to fix this fast

**Comment by jankoenig** [comment]
Fixed with the latest release! https://github.com/jovotech/jovo-framework/blob/master/CHANGELOG.md#2013-2019-01-29

**Pull request closed without merging**
