### PR TITLE
🐛 Analyze all $state elements for local route matches

### LINKED ISSUE #1380: @PrioritizedOverUnhandled() on not global handler gets ignored
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior

The [docs](https://www.jovo.tech/docs/routing#request-routing) says that handlers from all the components that are part of the $state stack and global handlers from all root components are selected for the matches array.
Now, I've ComponentA which has a global handler and a "local" one (both of them have @PrioritizedOverUnhandled() annotation) and ComponentB which has a local handler and UNHANDLED. Let's assume that the current $state stack is [ComponentA, ComponentB], so now I'm inside ComponentB.
If I invoke the intent handled by the global handler in ComponentA, the handler is correctly triggered. The problem is that if I invoke the other intent, the "local" handler isn't triggered and the request gets handled by the UNHANDLED in ComponentB.
From the docs, I assume that the local handler in ComponentA should be in the matches array as well, since ComponentA is in the current $state stack. But apparently, even if the local handler has @PrioritizedOverUnhandled() annotation, it isn't considered by the router.

## Current Behavior

You can see current behaviour in this repo [vocalime-base/jovo-4-router-issue](https://github.com/vocalime-base/jovo-4-router-issue).

Just run `npm test`.

## Your Environment

- Jovo Framework version used: 4.2.20

### PR DESCRIPTION
**Pull request by palle-k**
## Proposed Changes

This PR fixes #1380.
Previously, during route matching, only the topmost stack entry was analyzed for local matches. 
However, the documentation mentions that every stack entry should be matchable. 

When a component other than the topmost component of the $state stack is matched, the $state stack is unwound to that component.

**Note**: While this makes the behavior of Jovo consistent with the documentation, this is technically a breaking change.

## Types of Changes

- [x] Bug fix

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by palle-k** [comment]
@aswetlow please review.

Also: While this is out of scope for this PR, I am interested how global handlers (`@Handle({global: true, ...})`, **not** global components) fit into this picture.

When a global handler is matched that does not belong to any component of the $state stack, should the entire stack be replaced? Currently, global handlers just add components to the state stack.

**Comment by acerbisgianluca** [comment]
> When a global handler is matched that does not belong to any component of the $state stack, should the entire stack be replaced? Currently, global handlers just add components to the state stack.

I would like to leave my point of view about this. I think that Jovo should replace the entire stack in that case, because the user basically jumps out from the current state's scope and should restart from a new stack.

**Comment by palle-k** [comment]
This PR also potentially resolves #1211.

**Review by aswetlow — APPROVED** [review]

**Review by jankoenig — APPROVED** [review]
Thanks a lot @palle-k! 🎉

**Comment by jankoenig** [comment]
> > When a global handler is matched that does not belong to any component of the $state stack, should the entire stack be replaced? Currently, global handlers just add components to the state stack.
> 
> I would like to leave my point of view about this. I think that Jovo should replace the entire stack in that case, because the user basically jumps out from the current state's scope and should restart from a new stack.

This is something I've been thinking about for a while and it's difficult for me to reach a good decision here.

- I understand the idea of deleting the stack because some different path has been entered
- However, I'd love to be able to use global handlers as "detours" as well: e.g. you're in a checkout flow and then ask something like "what is the shipping cost again?", it answers that and then leads you back to the checkout flow

Nonetheless, we need a good way of cleaning up the state stack if a global handler is reached. Would love to discuss this more, maybe in a separate issue

Thanks for the input!

**Comment by palle-k** [comment]
> However, I'd love to be able to use global handlers as "detours" as well: e.g. you're in a checkout flow and then ask something like "what is the shipping cost again?", it answers that and then leads you back to the checkout flow

Could the `$resolve` method be adapted for this, so that there is a default resolution path that does not require any contract between the original component and the component with the global handler? 

This could also be interesting for delegation in general. Some components that I am writing only have a single resolution path, so having a default resolution here could be a nice to have as well. 

There could be a new special method name `CONTINUE` (like `START`/`UNHANDLED`), that would (if present) be executed upon default resolution.

**Pull request merged**
