### PR TITLE
Fixing issue where $gameEngine.respond would drop the session attributes

### PR DESCRIPTION
**Pull request by IGx89**
## Proposed changes
I discovered that when calling $gameEgine.respond (or $gadgetController.respond, which is identical), the resulting response doesn't contain the session attributes even though shouldEndSession !== true. It technically appears to be a bug in AlexaCore.output, however due to the design of the GameEngine plugin (not modifying shouldEndSession until after AlexaCore.output runs) I had to address it in GameEngine (and GadgetController).

I'm using $gameEngine.respond due to #316.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by aswetlow** [comment]
Thanks @IGx89

**Comment by IGx89** [comment]
@aswetlow, I'm not seeing this change in the latest jovo-platform-alexa release (v2.0.7). Could you see if it got missed somehow?

**Comment by IGx89** [comment]
Hi @aswetlow! Just following up on this. I've confirmed that these changes are indeed missing from the latest release. Would it be possible to have a release in the next day or two with this change?

**Comment by aswetlow** [comment]
Oh sorry, I missed the last comment. I had some issues while publishing the last version. My local /dist (which was published on NPM) has your changes, but they weren't uploaded to NPM. Will fix it tomorrow.

**Pull request merged**
