### PR TITLE
:sparkle: Add TextReplaceNluPlugin

### PR DESCRIPTION
**Pull request by rmtuckerphx**
## Proposed Changes

Add TextReplaceNluPlugin
Replace input text for all matches of a search value (string or RegExp) based on rules as an NLU preprocessor.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by rmtuckerphx** [comment]
@jankoenig @aswetlow This is a rework of a previous PR that you asked be its own plugin.
I ended up modifying the base `tsconfig.json` by adding `ES2021.String` so I could access `string.replaceAll()`. Could use some help figuring out the error I'm getting.

**Comment by aswetlow** [comment]
Hey Mark, thank you for the PR. `replaceAll` is very convenient, but wouldn't `str.replace(/regex/g)` fix the problem?

**Comment by rmtuckerphx** [comment]
@aswetlow - If search argument is a string, replaceAll() replaces all occurrences of search with replaceWith, while replace() only the first occurrence

I intended that string replacement would be the primary use case and added RegExp since it was supported by replaceAll.

Can you explain the reason behind the multiple tsconfig.build files and why replaceAll is failing?

**Comment by rmtuckerphx** [comment]
@aswetlow Fix this however you want. Either option works for me.

**Comment by aswetlow** [comment]
Sorry for the late response: 

Replacing `replaceAll`with `replace` should do the trick since you pass a `TextExp` object with a `g` flag.

**Pull request closed without merging**
