### PR TITLE
VoiceHero Analytics Integration

### PR DESCRIPTION
**Pull request by jkcchan**
## Proposed changes

Adds the VoiceHero Analytics Integration into the Jovo Framework.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by aswetlow** [comment]
Awesome! Thank you @jkcchan

**Comment by jankoenig** [comment]
Hey @jkcchan, seems like there was a problem with our markdown-to-web parser. Will investigate!

**Comment by jkcchan** [comment]
@jankoenig @aswetlow let us know if there's anything we can do! Thanks!

**Comment by jkcchan** [comment]
@jankoenig  @aswetlow It seems as though the package is not live on npm https://www.npmjs.com/package/jovo-analytics-voicehero

**Pull request merged**
